title:              365 Days of Data Science
email:              dataandstuff.blog@gmail.com
description:        Growing as a Data Scientist, One Day at a Time
author:             Christian Chow
baseurl:            "/365daysofdatascience"
url:                "https://chrischow.github.io/365daysofdatascience"

# Social Profiles
# twitter_username:   SBootstrap
github_username:    chrischow
# facebook_username:  StartBootstrap
# instagram_username:  
linkedin_username: christian-chow

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           7
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
